In [3]:
import numpy as np

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])


In [4]:
print("Multiply the individual elements of matrix")
print(np.multiply(x,y))

Multiply the individual elements of matrix
[[ 5 12]
 [21 32]]


In [5]:
print("Display transpose of the matrix")
print(x.transpose())
print(y.transpose())

Display transpose of the matrix
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
